### ISSUE TITLE
System Requirments

### ISSUE THREAD

**Issue by iskiselev** [daveaglick/Scripty#38]
It should be noted somewhere, that Scripty requires .Net 4.6 and (Microsoft Build Tools 2015 or Visual Studio 2015).
Probably it worth create better error messages if requirements are not met.
Right now:
- Before .Net 4.6 installed:

```
error MSB4018: The "ScriptyTask" task failed unexpectedly.
System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at Scripty.MsBuild.ScriptyTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext() 
```

Before Microsoft Build Tools 2015 installed:

```
Console:
Unhandled Exception:
   Cannot print exception string because Exception.ToString() failed.

Event Log:
Application: Scripty.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Security.SecurityException

Exception Info: System.IO.FileLoadException
   at Scripty.Core.ProjectTree.ProjectNode..ctor(Scripty.Core.ProjectTree.ProjectRoot, System.String, Scripty.Core.ProjectTree.ProjectNode, Microsoft.Build.Evaluation.ProjectItem)
   at Scripty.Core.ScriptEngine..ctor(System.String)
   at Scripty.Program.Run(System.String[])
   at Scripty.Program.Main(System.String[])

```

**Comment by Herdo** [comment]
At least for the VSIX:
This issue could be prevented by adding an environment constraint in the VSIX installer.
[The documentation](https://msdn.microsoft.com/en-us/library/hh696828.aspx) lists an example at the bottom of the page:

```
<Installation InstalledByMsi="false" AllUsers="false" SystemComponent="false" Scope="ProductExtension">
  <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[11.0, 12.0]" />
</Installation>
<Dependencies>
  <Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" d:Source="Manual" Version="[4.5,)" />
  <Dependency Id="Microsoft.VisualStudio.MPF.12.0" DisplayName="Visual Studio MPF 12.0" d:Source="Installed" Version="[12.0]" />
</Dependencies>
```

We might be able to use this to "require" VS >= 2015 and .NET Framework >= 4.6
